services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: jobber
      POSTGRES_PASSWORD: example
      POSTGRES_DB: jobberdb
    ports:
      - '5434:5432'

  pulsar:
    image: apachepulsar/pulsar
    command: >
      /pulsar/bin/pulsar standalone
    ports:
      - '6650:6650'
      - '8080:8080'
